### ISSUE TITLE
Old code 

### ISSUE THREAD

**Issue by deanmcginn** [italomaia/flask-empty#26]
I would like to point out that the code provided here, whilst being very fruitful for learning, doesn't conform to the newer version of Flask' s import statements.

Otherwise, this was extremely useful when I was trying to figure out how to separate routes into different files (so that I can group my routes), e.g. social_routes.py and api_routes.py

Thanks.

**Comment by italomaia** [comment]
Hello @deanmcginn What do you mean by that?

**Comment by italomaia-bk** [comment]
Would you mind sharing an example?

**Comment by italomaia** [comment]
Closed until an example is shown.
