### ISSUE TITLE
Update/add Flask-Security-Too

### ISSUE THREAD

**Issue by jwag956** [italomaia/flask-empty#35]
For the past 6 months I have been resurrecting Flask-Security - alas requiring my own fork at:
https://github.com/jwag956/flask-security

The original Flask-Security basically has stopped being maintained. I would like to either
ADD Flask-Security-Too as an additional supported extension OR replace Flask-Security.

I am willing to do the PR - just want guidance/approval of the idea.

**Comment by italomaia** [comment]
Hey @jwag956 how are you? So, last time I checked, flask-security had a new maintainer. That is exactly why I put it back into the extensions list (flask-security-fork was being used). I would like to try and involve them in the loop before taking action, given flask-security popularity. 
I'll also take some time to check your fork.

**Comment by italomaia** [comment]
https://github.com/mattupstate/flask-security/issues/854

**Comment by jwag956** [comment]
Thanks - yes - there was - but nothing came of that - which is why I started my own, at first I just released existing/approved PRs - then started modernizing.
You might want to scroll through this:
https://github.com/mattupstate/flask-security/issues/822

**Comment by italomaia** [comment]
Seems flask-security is left to the moths. Mind if we discuss flask-security-too a bit @jwag956 ? Gonna ping you privately for some details but would like to know a few things: 
Who are the **maintainers** for flask-security-too? What is the goal of the project (short, mid and long term)? 

PS: Thank you for opening this ticket and bringing my attention to this major issue.

**Comment by jwag956** [comment]
Sure - my email is on my profile.
A short overview is on my README:
https://github.com/jwag956/flask-security

Right now - it's just me - I have had around a dozen PRs - mostly small - although the two-factor auth PR was a large feature done by someone else.
Since I couldn't just take over 'Flask-Security' package - it will be a slow road to get 'noticed'. That's one reason I reached out to you - and have proposed a PR to flask-admin showing how to integrate with my fork (both flask-empty and flask-admin are very popular).

**Comment by italomaia** [comment]
It is done.
