### ISSUE TITLE
Error message: 'uses_cockroachdb' is undefined

### ISSUE THREAD

**Issue by rmontenegroo** [italomaia/flask-empty#38]
Maybe I am doing something wrong but my guess is that something is messy with cockroachdb option.

$ cookiecutter https://github.com/italomaia/flask-empty
You've downloaded /home/rodmonte/.cookiecutters/flask-empty before. Is it okay to delete and re-download it? [yes]: 
project_name [Your Project Name]: projeto
repo_name [projeto]: 
version [0.1]: 
use_sql_postgres [no]: 
use_sql_mysql [no]: 
use_sql_cockroachdb [no]: 
use_nosql_mongodb [no]: 
use_admin [no]: 
use_security [yes]: no
use_rest [yes]: 
use_socketio [yes]: 
use_async_tasks [yes]: 
use_http_mixin [yes]: 
create_index_view [yes]: 
Unable to create file 'Dockerfile'
Error message: 'uses_cockroachdb' is undefined
Context: {
    "cookiecutter": {
        "_template": "https://github.com/italomaia/flask-empty",
        "create_index_view": "yes",
        "project_name": "projeto",
        "repo_name": "projeto",
        "use_admin": "no",
        "use_async_tasks": "yes",
        "use_http_mixin": "yes",
        "use_nosql_mongodb": "no",
        "use_rest": "yes",
        "use_security": "no",
        "use_socketio": "yes",
        "use_sql_cockroachdb": "no",
        "use_sql_mysql": "no",
        "use_sql_postgres": "no",
        "version": "0.1"
    }
}

**Comment by italomaia** [comment]
Lemme check ...

**Comment by italomaia** [comment]
Ok, there is a bug. Let me fix this real quick.

**Comment by italomaia** [comment]
Develop branch was already fixed. Now I updated master. Can you try again?

**Comment by rmontenegroo** [comment]
Quick answer: I can build the project now. Thx
