### ISSUE TITLE
ModuleNotFoundError: No module named 'flask.ext'

### ISSUE THREAD

**Issue by MariaCarolinass** [italomaia/flask-empty#39]
Olá, tentei instalar o seu projeto em minha máquina, para conhecer melhor, mas me deparei com o erro descrito no título.
Segue o meu passo a passo: ativei o `virtualenv`, logo em seguida, instalei o arquivo `requirements.txt` que fica na página examples, e, então executei `python manage.py create_db`. 

Mensagem de erro: `Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from flask.ext import script
ModuleNotFoundError: No module named 'flask.ext'`

A seguir, adicionei `export FLASK_APP=manage.py` e, então, executei `flask run`.

Mensagem de erro: `ImportError: No module named ext`

Pesquisei um pouco e encontrei que flask.ext não está em uso:

- https://stackoverflow.com/questions/55023231/importerror-no-module-named-flask-ext
- https://github.com/lmeunier/flask-compressor/issues/3
- https://stackoverflow.com/questions/33675594/importerror-no-module-named-flask-ext-script

**Comment by italomaia** [comment]
Oi Carolina, tudo bom? Vou dar uma olhada. Talvez precise atualizar o flask-empty.

**Comment by italomaia** [comment]
Oi @MariaCarolinass Por um acaso você incorreu nesse erro ao tentar rodar o "blog_example" ou foi após criar um projeto utilizando o boilerplate?

**Comment by MariaCarolinass** [comment]
Ao rodar o blog_example

**Comment by italomaia** [comment]
Oi @MariaCarolinass poderia testar novamente? Deve estar tudo corrigido na nova versão.

**Comment by italomaia** [comment]
Vou fechar a issue. @MariaCarolinass caso o problema persista, fique à vontade para reabrir a issue.
