### ISSUE TITLE
Missing files after running cookiecutter

### ISSUE THREAD

**Issue by kevinp2** [italomaia/flask-empty#41]
After following the procedures in README.md , I can start the server, but only get a Page Not Found error when I browse to it.

In trying to troubleshoot this, I found that the following files are referred to in README.md but do not exist in the tree that was created:

1) **.venv** referred to in this section:
```
# loads env variables and runs the project in development mode
source .venv && make run-dev
```

2) **.env** referred to in this section:

`Be aware that you might need to tweak the environment variables for production mode. **The are available at .env** and Dockerfile. I
`
3) **database.py** referred to in this section:

`While creating your project, Flask-Empty will ask you if you wish to enable SQL support. Confirm if you do so and Flask-SQLAlchemy will be available and configured through database.py`

Note that I requested sqlite support, so if I understand correctly, database.py should have been created?

**Comment by italomaia** [comment]
Good catch. Let me check this. database.py is not needed anymore. All configuration is held in config.py.

**Comment by italomaia** [comment]
I just released a new version. Care to try it @kevinp2 ?

**Comment by italomaia** [comment]
Oh well, open ticket again if problem is not solved.
