### ISSUE TITLE
ValueError: Datastore must be provided

### ISSUE THREAD

**Issue by howardjones** [italomaia/flask-empty#46]
Just hitting return to everything in the default template (after the names) and `make run-dev` produces this error from flask-security.

I don't see any mention of "datastore" in the config file. It looks like the `empty` module calls the `init_app()` method of each extension with no args, and flask_security doesn't like that?

**Comment by italomaia** [comment]
Just took a look. Something weird is happening under the hood with flask-security; got to take a deeper look.
This might take a while. If you're reading this and got a workaround, please, share.

**Comment by italomaia** [comment]
Pushed a fix; please try it and reopen the issue if the problem persists. Gonna reach out to flask-security author and see how can we improve the integration here.
